import { GoogleGenAI } from "@google/genai";

/**
 * Generates a landscaped version of the provided garden image.
 * @param base64Image The base64 string of the original image.
 * @param promptDescription A text description of the desired style.
 * @returns A promise resolving to the base64 string of the generated image.
 */
export const generateLandscape = async (
  base64Image: string,
  promptDescription: string
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  try {
    // Clean the base64 string if it contains the data header
    const cleanedBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
    const mimeType = 'image/jpeg'; 

    const fullPrompt = `
      Act as a world-class landscape architect. 
      Redesign the outdoor space shown in the image.
      Keep the main structural elements of the house/buildings (if visible) to ensure realism.
      Replace the existing ground cover, plants, and decor with the following style:
      "${promptDescription}"
      Ensure the lighting is natural and the result looks photorealistic.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image', 
      contents: {
        parts: [
          {
            text: fullPrompt,
          },
          {
            inlineData: {
              mimeType: mimeType,
              data: cleanedBase64,
            },
          },
        ],
      }
    });

    // Iterate through parts to find the image output
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    throw new Error(error.message || "Failed to generate landscape design.");
  }
};
